IMAGE_NAME = "generic/ubuntu1604"
ssh_pub_key = File.readlines("ssh_keys/key.pub").first.strip

Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
    config.vm.provision "shell", path: "provision/no-ipv6.sh", privileged: true
    config.vm.provision "shell", path: "provision/dns.sh", privileged: true
    config.vm.provision "shell", path: "provision/packages.sh", privileged: true
    config.vm.provision "shell", path: "provision/append-bashrc.sh", privileged: false

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 3
    end

    config.vm.provider "libvirt" do |v|
        v.memory = 4096
        v.cpus = 3
        v.driver = "kvm"
        v.qemu_use_session = false
    end

    config.vm.define "manager" do |node|
        node.vm.box = IMAGE_NAME
        node.vm.hostname = "manager"
        node.vm.network "private_network", ip: "192.168.100.10"
        #node.vm.network "forwarded_port", guest: 6443, host: 6443, protocol: "tcp"
    end

    (1..2).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.hostname = "node-#{i}"
            node.vm.network "private_network", ip: "192.168.100.#{i + 10}"
        end
    end
end
