---
- name: Requirements
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Disable swap
      ansible.builtin.include_tasks: tasks/disable-swap.yml

    - name: Ensure kernel modules are always loaded
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s-reqs.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          overlay
          br_netfilter

    - name: Ensure sysctl settings
      ansible.builtin.copy:
        dest: /etc/sysctl.d/98-k8s-reqs.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
          vm.swappiness = 0

    - name: Stop and disable ufw.service
      ansible.builtin.systemd:
        name: ufw.service
        state: stopped
        enabled: false

    - name: Reboot
      ansible.builtin.reboot:
