---
# https://cri-o.io/
# https://github.com/cri-o/cri-o/blob/main/install.md#readme
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/

- name: Install cri-o
  hosts: all
  become: true
  become_user: root
  vars:
    crio_version: "1.28"
    crio_os: "xUbuntu_22.04"
  tasks:
    - name: Ensure required dependencies are installed
      ansible.builtin.apt:
        name:
          - gnupg
          - libseccomp2
        state: present
        update_cache: true

    - name: Add cri-o libcontainers:stable key and repo
      block:
        # curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | apt-key add -
        - name: Keyring
          ansible.builtin.apt_key:
            url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ crio_os }}/Release.key
            state: present
        # echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
        - name: Repo
          ansible.builtin.apt_repository:
            repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ crio_os }}/ /"
            filename: devel:kubic:libcontainers:stable
            state: present

    - name: Add cri-o libcontainers:stable:cri-o key and repo
      block:
        # curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/Release.key | apt-key add -
        - name: Keyring
          ansible.builtin.apt_key:
            url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/{{ crio_os }}/Release.key
            state: present
        # echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list
        - name: Repo
          ansible.builtin.apt_repository:
            repo: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/{{ crio_os }}/ /"
            filename: devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}
            state: present

    # # If you'd like to use the distribution's runc, you'll have to add the file:
    # - name: Add crio configuration for runc
    #   ansible.builtin.copy:
    #     dest: /etc/crio/crio.conf.d/runc.toml
    #     content: |
    #       [crio.runtime.runtimes.runc]
    #       runtime_path = ""
    #       runtime_type = "oci"
    #       runtime_root = "/run/runc"

    - name: Ensure crio packages are installed
      ansible.builtin.apt:
        name:
          - cri-o
          - cri-o-runc
        state: present
        update_cache: true

    # # CRI-O uses the systemd cgroup driver per default, which is likely to work fine for you.
    # # To switch to the cgroupfs cgroup driver, either edit /etc/crio/crio.conf or place a drop-in configuration
    # # in /etc/crio/crio.conf.d/02-cgroup-manager.conf, for example:
    # - name: Switch to the cgroupfs cgroup driver
    #   ansible.builtin.copy:
    #     dest: /etc/crio/crio.conf.d/02-cgroup-driver.conf
    #     content: |
    #       [crio.runtime]
    #       conmon_cgroup = "pod"
    #       cgroup_manager = "cgroupfs"
    - name: Set cgroup driver
      ansible.builtin.copy:
        dest: /etc/crio/crio.conf.d/02-cgroup-driver.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          [crio.runtime]
          cgroup_manager = "systemd"

    # # https://kubernetes.io/docs/setup/production-environment/container-runtimes/#override-pause-image-cri-o
    - name: Overriding the sandbox (pause) image
      ansible.builtin.copy:
        dest: /etc/crio/crio.conf.d/03-override-pause-image.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          [crio.image]
          pause_image="registry.k8s.io/pause:3.6"

    - name: Reload crio service
      ansible.builtin.systemd:
        name: crio.service
        state: restarted
        enabled: true
        daemon_reload: true
