---
- name: Install cilium cli node-0
  hosts: kube-node-0
  become: true
  become_user: root
  tasks:
    - name: Install cilium cli
      # https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/#install-the-cilium-cli
      ansible.builtin.shell:
        cmd: |
          CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
          CLI_ARCH=amd64
          if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
          curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz
          tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
          rm cilium-linux-${CLI_ARCH}.tar.gz
        creates: /usr/local/bin/cilium
        chdir: /tmp/

- name: Install cilium
  hosts: kube-node-0
  become: true
  become_user: ubuntu
  vars:
    cilium_version: 1.14.1
  tasks:
    # https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/#install-cilium
    - name: Install cilium
      ansible.builtin.shell:
        cmd: |
          cilium install --version {{ cilium_version }} --wait
          cilium status --wait
        creates: /var/run/cilium/cilium.pid
