---
- name: Install calico in node-0
  hosts: kube-node-0
  become: true
  become_user: ubuntu
  tasks:
    - name: Install calico
      # https://docs.tigera.io/calico/latest/getting-started/kubernetes/self-managed-onprem/onpremises#install-calico
      ansible.builtin.shell:
        cmd: |
          kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/tigera-operator.yaml
          curl https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/custom-resources.yaml -O
          sed -i 's/192.168.0.0/10.42.0.0/g' custom-resources.yaml
          kubectl create -f custom-resources.yaml
          touch /opt/calico_installed
        creates: /opt/calico_installed
        chdir: /tmp/
