---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Ensure requirements are installed
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages: [ "apt-transport-https", "ca-certificates", "curl" ]

  - name: "Add kubernetes repo key"
    ansible.builtin.apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
  - name: "Add kubernetes repo"
    ansible.builtin.apt_repository:
      repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
      state: present
      update_cache: true
      filename: kubernetes.list
  - name: Install Kubernetes binaries
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet=1.21.0-00
        - kubeadm=1.21.0-00
        - kubectl=1.21.0-00
    register: apt_install_result
  - name: Configure node ip
    ansible.builtin.lineinfile:
      state: present
      create: true
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ hostvars[inventory_hostname]['ansible_ssh_host'] }}
    register: kubelet_file_result
  - name: Restart kubelet
    ansible.builtin.systemd:
      name: kubelet
      state: restarted
      enabled: yes
      daemon_reload: yes
    when: apt_install_result.changed or kubelet_file_result.changed
